### ISSUE TITLE
Simpleio.Servo.set_angle() does not exist

### ISSUE THREAD

**Issue by adamdrenth** [adafruit/METROX-Examples-and-Project-Sketches#5]
All the code for servo's using simpleio should use the angle property.

servo = Servo(board.D9)
servo.set_angle(90) # Incorrect and causes a compile error
servo.angle = 90      # Correct and moves the arm to 90 degree position

**Comment by brentru** [comment]
Thanks for this - I didn't merge in the updated code from my local machine to this repo before now. 

The [servo code](https://github.com/adafruit/METROX-Examples-and-Project-Sketches/blob/master/circuitpython/CIRC04/servo.py#L12) has been updated to use the [CircuitPython Motor Library](https://github.com/adafruit/Adafruit_CircuitPython_Motor) instead of Simpleio's Servo method.
